name: Release Terrabutler

on:  
  push:
    tags:
      - '*'

jobs:
  release-terrabutler:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Current Tag
        uses: WyriHaximus/github-action-get-previous-tag@master
        id: tag
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set version based on tag
        run: |
          sed -i 's/dev/${{ steps.tag.outputs.tag }}/g' terrabutler/__init__.py
      - name: Build Python Module
        run: |
          pip install -r requirements.txt pyinstaller
          pyinstaller --clean -y --dist ./dist/terrabutler --workpath /tmp terrabutler/terrabutler.spec
          mv dist/terrabutler/terrabutler dist/terrabutler/dist
      - name: Copy needed files to build directory
        run: |
          cp README.md dist/terrabutler
          cp LICENSE dist/terrabutler
          cp scripts/install dist/terrabutler
      - name: Create archive of build (.tar.gz)
        uses: sibiraj-s/action-archiver@v1
        with:
          working-directory: "./"
          path: "dist"
          format: tar
          gzip: true
          output: terrabutler-linux-x86_64-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Add artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          files: terrabutler-linux-x86_64-${{ steps.tag.outputs.tag }}.tar.gz
